on: [push, pull_request]
name: Test

jobs:
  # Cross-compilation checks for platforms we can't test natively
  cross-compile:
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: js
            goarch: wasm
          - goos: linux
            goarch: arm
            goarm: '7'
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: amd64
        go:
          - '1.24.x'
          - '1.25.x'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Go version
        run: go version

      - name: Go vet
        run: go vet -v ./...
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}

      - name: Build check
        run: go build ./...
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
